let class12th = [
    {
        uid: 0,
        uname: "강건희",
        ugener: "남자",
        uage: 27,
        uzs: "용",
        umbti: "INTP",
        umarried: false,
        ulike: ["게임", "볼링", "운동"],
        umotto: "이 또한 지나가리",
        uphoto: "강건희.png"
    },
    {
        uid: 1,
        uname: "최희정",
        ugener: "여자",
        uage: 27,
        uzs: "용",
        umbti: "ENFJ",
        umarried: false,
        ulike: ["요가", "여행"],
        umotto: "긍정적으로 살자",
        uphoto: "최희정.png"
    },
    {
        uid: 2,
        uname: "장윤서",
        ugener: "여자",
        uage: 27,
        uzs: "용",
        umbti: "INTJ",
        umarried: false,
        ulike: ["요리", "산책"],
        umotto: "현재에 집중하자",
        uphoto: "장윤서.png"
    },
    {
        uid: 3,
        uname: "이은지",
        ugener: "여자",
        uage: 29,
        uzs: "호랑이",
        umbti: "ISFP",
        umarried: false,
        ulike: ["사진", "눕방"],
        umotto: "당당하게 살자",
        uphoto: "이은지.png"
    },
    {
        uid: 4,
        uname: "조성현",
        ugener: "여자",
        uage: 28,
        uzs: "호랑이",
        umbti: "ESTJ",
        umarried: false,
        ulike: ["운동", "게임"],
        umotto: "그냥살자",
        uphoto: "조성현.png"
    },
    {
        uid: 5,
        uname: "김민지B",
        ugener: "여자",
        uage: 25,
        uzs: "말",
        umbti: "ISTP",
        umarried: false,
        ulike: ["음악듣기", "운동", "뜨개질", "영화보기"],
        umotto: "흘러가는대로 살자",
        uphoto: "김민지B.png"
    },
    {
        uid: 6,
        uname: "배민지",
        ugener: "여자",
        uage: 35,
        uzs: "원숭이",
        umbti: "ESTP",
        umarried: false,
        ulike: ["춤", "사진", "산책"],
        umotto: "변명대신 결과",
        uphoto: "배민지.png"
    },
    {
        uid: 7,
        uname: "권오영",
        ugener: "남자",
        uage: 33,
        uzs: "개",
        umbti: "INFP",
        umarried: false,
        ulike: ["드럼", "운동", "독서"],
        umotto: "태도를 똑바로 하자",
        uphoto: "권오영.png"
    },
    {
        uid: 8,
        uname: "윤예영",
        ugener: "여자",
        uage: 40,
        uzs: "소",
        umbti: "ISTJ",
        umarried: true,
        ulike: ["요리", "공예", "독서"],
        umotto: "열심히 살자",
        uphoto: "윤예영.png"
    },
    {
        uid: 9,
        uname: "연진주",
        ugener: "여자",
        uage: 31,
        uzs: "쥐",
        umbti: "ISFJ",
        umarried: false,
        ulike: ["여행", "산책", "카페가기"],
        umotto: "서두르지 말자",
        uphoto: "연진주.png"
    },
    {
        uid: 10,
        uname: "정서현",
        ugener: "여자",
        uage: 29,
        uzs: "호랑이",
        umbti: "ISTJ",
        umarried: false,
        ulike: ["여행", "사진", "도예"],
        umotto: "시작이 반이다",
        uphoto: "정서현.png"
    },
    {
        uid: 11,
        uname: "최예슬",
        ugener: "여자",
        uage: 28,
        uzs: "토끼",
        umbti: "ESTJ",
        umarried: false,
        ulike: ["산책", "독서", "여행"],
        umotto: "기분이 태도가 되지말자",
        uphoto: "최예슬.png"
    },
    {
        uid: 12,
        uname: "김민지A",
        ugener: "여자",
        uage: 28,
        uzs: "토끼",
        umbti: "ISFP",
        umarried: false,
        ulike: ["복싱", "영화관람"],
        umotto: "그래도 열심히 해야지",
        uphoto: "김민지A.png"
    },
    {
        uid: 13,
        uname: "김선영",
        ugener: "여자",
        uage: 33,
        uzs: "개",
        umbti: "ISTP",
        umarried: false,
        ulike: ["베이킹", "낚시", "드라이브", "등산"],
        umotto: "모든 선택에 후회하지 말자",
        uphoto: "김선영.png"
    },
    {
        uid: 14,
        uname: "김가희",
        ugener: "여자",
        uage: 37,
        uzs: "말",
        umbti: "ESFJ",
        umarried: true,
        ulike: ["아이쇼핑", "드라이브", "카페"],
        umotto: "즐겁게 살자",
        uphoto: "김가희.png"
    },
    {
        uid: 15,
        uname: "정현진",
        ugener: "남자",
        uage: 40,
        uzs: "소",
        umbti: "INFP",
        umarried: false,
        ulike: ["공부", "부업찾기", "게임", "카페", "산책"],
        umotto: "주식은 꼭 해야하는 것",
        uphoto: "정현진.png"
    }
]